server: 
  port: 9091
  
  
spring:  application:    name: DEPARTMENT-SERVICE
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulltZone: http://localhost:8761/eureka/
   
  instance:
    hostname: localhost