server: 
  port: 9002
  
  
spring:
  application:
    name: USER-SERVICE
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaulltZone: http://localhost:8761/eureka/
   
  instance:    hostname: localhost
    
    